//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public System.DateTime BookingDateTime { get; set; }
        public int NumberOfGuests { get; set; }
        public Nullable<int> TableId { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual RestaurantTable RestaurantTable { get; set; }
    }
}
