//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamagedStock
    {
        public int Id { get; set; }
        public int IngredientId { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime DamageDate { get; set; }
        public string Reason { get; set; }
        public int ReportedByEmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
