//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryZone
    {
        public int Id { get; set; }
        public string ZoneName { get; set; }
        public string District { get; set; }
        public string Ward { get; set; }
        public decimal DeliveryFee { get; set; }
        public decimal MinOrderForFreeDelivery { get; set; }
        public int EstimatedTime { get; set; }
        public Nullable<decimal> MaxDistance { get; set; }
        public bool IsActive { get; set; }
        public int DisplayOrder { get; set; }
    }
}
