//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryAssignment
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ShipperId { get; set; }
        public System.DateTime AssignedTime { get; set; }
        public Nullable<System.DateTime> PickupTime { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> CurrentLatitude { get; set; }
        public Nullable<decimal> CurrentLongitude { get; set; }
        public Nullable<System.DateTime> EstimatedArrival { get; set; }
        public Nullable<decimal> ActualDistance { get; set; }
        public decimal DeliveryFee { get; set; }
        public decimal ShipperEarning { get; set; }
        public string Notes { get; set; }
        public string FailureReason { get; set; }
        public string ProofImageUrl { get; set; }
        public Nullable<int> CustomerRating { get; set; }
        public string CustomerFeedback { get; set; }
    
        public virtual CustomerOrder CustomerOrder { get; set; }
        public virtual Shipper Shipper { get; set; }
    }
}
