//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public int Id { get; set; }
        public string EmailType { get; set; }
        public string ToEmail { get; set; }
        public string ToName { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Status { get; set; }
        public string ErrorMessage { get; set; }
        public int RetryCount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public string ReferenceType { get; set; }
    }
}
