//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitchenOrderTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KitchenOrderTicket()
        {
            this.KitchenOrderItem = new HashSet<KitchenOrderItem>();
        }
    
        public int Id { get; set; }
        public string TicketCode { get; set; }
        public int OrderId { get; set; }
        public int TableId { get; set; }
        public string Status { get; set; }
        public int Priority { get; set; }
        public string SpecialNotes { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> StartedTime { get; set; }
        public Nullable<System.DateTime> CompletedTime { get; set; }
        public int EstimatedMinutes { get; set; }
        public Nullable<int> AssignedChefId { get; set; }
        public string KitchenStation { get; set; }
        public bool IsPrinted { get; set; }
        public int PrintCount { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitchenOrderItem> KitchenOrderItem { get; set; }
        public virtual Order Order { get; set; }
        public virtual RestaurantTable RestaurantTable { get; set; }
    }
}
