//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitchenOrderItem
    {
        public int Id { get; set; }
        public int KitchenOrderTicketId { get; set; }
        public Nullable<int> OrderDetailId { get; set; }
        public int MenuItemId { get; set; }
        public string ItemName { get; set; }
        public int Quantity { get; set; }
        public int CompletedQuantity { get; set; }
        public string Status { get; set; }
        public string CustomerNotes { get; set; }
        public string KitchenNotes { get; set; }
        public Nullable<System.DateTime> StartedTime { get; set; }
        public Nullable<System.DateTime> CompletedTime { get; set; }
        public string Station { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
        public virtual KitchenOrderTicket KitchenOrderTicket { get; set; }
    }
}
