//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuComboItem
    {
        public int Id { get; set; }
        public int MenuComboId { get; set; }
        public int MenuItemId { get; set; }
        public int Quantity { get; set; }
    
        public virtual MenuCombo MenuCombo { get; set; }
        public virtual MenuItem MenuItem { get; set; }
    }
}
