//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NhaHangLDPEntities : DbContext
    {
        public NhaHangLDPEntities()
            : base("name=NhaHangLDPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AppSetting> AppSetting { get; set; }
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<CashierShift> CashierShift { get; set; }
        public virtual DbSet<DamagedStock> DamagedStock { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Ingredient> Ingredient { get; set; }
        public virtual DbSet<MenuCombo> MenuCombo { get; set; }
        public virtual DbSet<MenuComboItem> MenuComboItem { get; set; }
        public virtual DbSet<MenuItem> MenuItem { get; set; }
        public virtual DbSet<MenuItemIngredient> MenuItemIngredient { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<PriceHistory> PriceHistory { get; set; }
        public virtual DbSet<RestaurantTable> RestaurantTable { get; set; }
        public virtual DbSet<ReturnBill> ReturnBill { get; set; }
        public virtual DbSet<ReturnBillDetail> ReturnBillDetail { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<ShiftSupportStaff> ShiftSupportStaff { get; set; }
        public virtual DbSet<StockInbound> StockInbound { get; set; }
        public virtual DbSet<StockInboundDetail> StockInboundDetail { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<TableArea> TableArea { get; set; }
        public virtual DbSet<EmailConfig> EmailConfig { get; set; }
        public virtual DbSet<EmailLog> EmailLog { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplate { get; set; }
        public virtual DbSet<KitchenOrderItem> KitchenOrderItem { get; set; }
        public virtual DbSet<KitchenOrderTicket> KitchenOrderTicket { get; set; }
        public virtual DbSet<KitchenStation> KitchenStation { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Promotion> Promotion { get; set; }
        public virtual DbSet<PromotionUsage> PromotionUsage { get; set; }
        public virtual DbSet<QROrder> QROrder { get; set; }
        public virtual DbSet<QROrderDetail> QROrderDetail { get; set; }
        public virtual DbSet<TableSession> TableSession { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<EmployeeContract> EmployeeContract { get; set; }
        public virtual DbSet<EmployeeSchedule> EmployeeSchedule { get; set; }
        public virtual DbSet<LeaveRequest> LeaveRequest { get; set; }
        public virtual DbSet<Payroll> Payroll { get; set; }
        public virtual DbSet<PerformanceReview> PerformanceReview { get; set; }
        public virtual DbSet<WorkShift> WorkShift { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<CartItem> CartItem { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddress { get; set; }
        public virtual DbSet<CustomerNotification> CustomerNotification { get; set; }
        public virtual DbSet<CustomerOrder> CustomerOrder { get; set; }
        public virtual DbSet<CustomerOrderDetail> CustomerOrderDetail { get; set; }
        public virtual DbSet<DeliveryAssignment> DeliveryAssignment { get; set; }
        public virtual DbSet<DeliverySettings> DeliverySettings { get; set; }
        public virtual DbSet<DeliveryZone> DeliveryZone { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<Shipper> Shipper { get; set; }
        public virtual DbSet<Voucher> Voucher { get; set; }
        public virtual DbSet<VoucherUsage> VoucherUsage { get; set; }
        public virtual DbSet<Wishlist> Wishlist { get; set; }
        public virtual DbSet<SupportConversation> SupportConversation { get; set; }
        public virtual DbSet<SupportMessage> SupportMessage { get; set; }
    }
}
