//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceReview
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int ReviewerId { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public string ReviewPeriod { get; set; }
        public int ServiceQuality { get; set; }
        public int Punctuality { get; set; }
        public int Teamwork { get; set; }
        public int Communication { get; set; }
        public int WorkEfficiency { get; set; }
        public Nullable<decimal> OverallScore { get; set; }
        public string Strengths { get; set; }
        public string AreasToImprove { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
