//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionUsage
    {
        public int Id { get; set; }
        public int PromotionId { get; set; }
        public Nullable<int> BillId { get; set; }
        public string CustomerPhone { get; set; }
        public decimal DiscountApplied { get; set; }
        public System.DateTime UsedDate { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
