//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QROrderDetail
    {
        public int Id { get; set; }
        public int QROrderId { get; set; }
        public int MenuItemId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public string ItemNotes { get; set; }
        public string ItemStatus { get; set; }
        public System.DateTime AddedTime { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
        public virtual QROrder QROrder { get; set; }
    }
}
