//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QROrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QROrder()
        {
            this.QROrderDetail = new HashSet<QROrderDetail>();
        }
    
        public int Id { get; set; }
        public string QROrderCode { get; set; }
        public string SessionToken { get; set; }
        public int TableId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> SubmittedTime { get; set; }
        public Nullable<System.DateTime> ConfirmedTime { get; set; }
        public Nullable<System.DateTime> CompletedTime { get; set; }
        public Nullable<int> LinkedOrderId { get; set; }
        public Nullable<int> ConfirmedByEmployeeId { get; set; }
        public string AppliedPromotionCode { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
        public virtual RestaurantTable RestaurantTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QROrderDetail> QROrderDetail { get; set; }
    }
}
