//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public string ReservationCode { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerEmail { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public System.TimeSpan ReservationTime { get; set; }
        public int NumberOfGuests { get; set; }
        public Nullable<int> TableId { get; set; }
        public string TablePreference { get; set; }
        public string SpecialRequests { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public bool DepositPaid { get; set; }
        public string CancelReason { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
