//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnBillDetail
    {
        public int ReturnBillDetailID { get; set; }
        public int ReturnBillID { get; set; }
        public int MenuItemID { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public bool IsDamaged { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
        public virtual ReturnBill ReturnBill { get; set; }
    }
}
