//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReturnBill()
        {
            this.ReturnBillDetail = new HashSet<ReturnBillDetail>();
        }
    
        public int ReturnBillID { get; set; }
        public int OriginalBillID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public decimal TotalRefundAmount { get; set; }
        public string Reason { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnBillDetail> ReturnBillDetail { get; set; }
    }
}
