//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int MenuItemId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public int Rating { get; set; }
        public string Comment { get; set; }
        public string ImageUrls { get; set; }
        public int LikesCount { get; set; }
        public bool IsVerifiedPurchase { get; set; }
        public string AdminReply { get; set; }
        public Nullable<System.DateTime> AdminReplyDate { get; set; }
        public bool IsApproved { get; set; }
        public bool IsHidden { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerOrder CustomerOrder { get; set; }
        public virtual MenuItem MenuItem { get; set; }
    }
}
