//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInboundDetail
    {
        public int Id { get; set; }
        public int StockInboundId { get; set; }
        public int IngredientId { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string BatchNumber { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual StockInbound StockInbound { get; set; }
    }
}
