//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInbound
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockInbound()
        {
            this.StockInboundDetail = new HashSet<StockInboundDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime InboundDate { get; set; }
        public decimal TotalCost { get; set; }
        public string Notes { get; set; }
        public string InboundCode { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockInboundDetail> StockInboundDetail { get; set; }
    }
}
