//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportConversation
    {
        public int Id { get; set; }
        public string ConversationCode { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<int> AssignedStaffId { get; set; }
        public string Status { get; set; }
        public string Subject { get; set; }
        public string Priority { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> LastMessageTime { get; set; }
        public Nullable<int> CustomerRating { get; set; }
        public string CustomerFeedback { get; set; }
        public string InternalNotes { get; set; }
        public string Tags { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
