//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportMessage
    {
        public int Id { get; set; }
        public string SenderId { get; set; }
        public string SenderType { get; set; }
        public string SenderName { get; set; }
        public string RecipientId { get; set; }
        public string RecipientType { get; set; }
        public string Message { get; set; }
        public string MessageType { get; set; }
        public string AttachmentUrl { get; set; }
        public System.DateTime SentTime { get; set; }
        public bool IsRead { get; set; }
        public Nullable<System.DateTime> ReadTime { get; set; }
        public string ConversationId { get; set; }
        public string Metadata { get; set; }
    }
}
