//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangLDP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherUsage
    {
        public int Id { get; set; }
        public int VoucherId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int OrderId { get; set; }
        public decimal DiscountAmount { get; set; }
        public System.DateTime UsedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerOrder CustomerOrder { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
